name: Teste CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o repositório
        uses: actions/checkout@v3

      - name: Verificar versão do Node
        run: node -v

      - name: Exibir mensagem de sucesso
        run: echo "🎉 Pipeline GitHub Actions funcionando com sucesso!"
